#pragma once

enum class Type {
	IntegerKeyword,
	BooleanKeyword,
	StringKeyword,
	ArrayKeyword,
	IfKeyword,
	WhileKeyword,
	AndKeyword,
	OrKeyword,
	TrueKeyword,
	FalseKeyword,
	AndOrKeyword,
	TrueFalseKeyword,

	AssignmentOperation,
	EqualityOperation,
	InequalityOperation,
	MoreOperation,
	LessOperation,
	MoreOrEqualOperation,
	LessOrEqualOperation,
	AdditionOperation,
	SubtractionOperation,
	MultiplicationOperation,
	DivisionOperation,
	ExpressionOperation,
	ComparisonOperation,

	NewLineSymbol,
	OpeningBraceSymbol,
	ClosingBraceSymbol,
	OpeningParenthesisSymbol,
	ClosingParenthesisSymbol,
	OpeningSquareBracketSymbol,
	ClosingSquareBracketSymbol,

	Program,
	Element,
	IfBlock,
	WhileBlock,
	Line,
	Condition,
	Assign,
	Expression,
	Comparison,
	Name,
	VariableDeclaration,
	Number,
	Word,
	Letter,
	Digit,
	Array,
	ArrayElement,
	String
};

